### ISSUE TITLE
Add initial version of map.h

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#10]
This file defines the abstract API for the public function provided by both hashmap and treemap ADTs

**Comment by powderflask** [comment]
Added prototypes for first 2 functions from the API spec.
TODO: add rest of proto-types.

**Comment by ttiim** [comment]
how do i assign myself to this issue?

**Comment by powderflask** [comment]
Look to menu on right - top: Assignees - click tool-gear - tick self.

**Comment by ttiim** [comment]
strange... i know exactly where you mean. No gearbox is available for me though.

**Comment by Karan-Nedungadi** [comment]
I'm having a similiar problem as Tim. I think there is supposed to be a gear symbol by the "Assignes" title. 
![screenshot 42](https://user-images.githubusercontent.com/36754565/38149565-d8327048-340f-11e8-8875-1d004f05c10e.png)

**Comment by powderflask** [comment]
OK - I adjusted the repo settings - hopefully you all have the correct permissions now - please let me know.

**Comment by ttiim** [comment]
behaving nominal now. Thanks

**Comment by powderflask** [comment]
Great -- please alert me if you run into other issues -- these projects have lots of settings that need to be just right to allow the team to function together as intended.  thanks Tim.
