### ISSUE TITLE
hashmap.c hash function produces negative hash value

### ISSUE THREAD

**Issue by rickycheung2** [CapU-CompSci/MapADT-220-2018#103]
When we use mapindex(), negative hash value modulus produces negative index, which causes seg fault when we try to access a negative index.

e.g. The word "marble-sanded" in wordcloud.txt produces a negative hash, and an index of -80. When accessing wordmap[-80], it gives seg fault.

**Comment by rickycheung2** [comment]
Not sure how to properly fix this, but as a temporary fix, mapindex() now returns absolute value of the calculated index.

**Comment by Karan-Nedungadi** [comment]
Ya the % operator does not like negative values. 
I think we got two options:
1. Bad idea: force hmapfunction() to strictly output positive values (I don't know the functionality of hashmap.c so no clue if this is a good idea)
2.  Good idea (maybe?) shift it by the array size then use the modulus operator:
index = (hash + ARRAY_SIZE) % ARRAY_SIZE;
it will give you a positive value for negative hashes and, for positive hashes, give you the same value.
2%10 = (2+10)%10

**Comment by powderflask** [comment]
Either has the same net effect.  I like the absolute value solution -- cleaner.
Use abs() for integer absolute value of hash before applying modulus operator.

**Comment by powderflask** [comment]
I believe the issue was use of a signed long when an unsigned value was required.
I think someone asked me in the term why you would ever need an unsigned value -- here's a perfect circumstance.
Forgot to mention I fixed this in commit 91b1044
