### ISSUE TITLE
Found an issue with mapRemove and TwoChildDelete

### ISSUE THREAD

**Issue by leviffs** [CapU-CompSci/MapADT-220-2018#104]
mapRemove calls twoChildDelete and twoChildDelete calls mapRemove. also mapRemove has the same issue as a lot of the other functions in that it improperly compares keys. Use the new keyCompare function to fix it. I am going to work on twoChildDelete.

**Comment by leviffs** [comment]
TwoChildDelete is now working, Ill push the changes but I wont close the issue yet

**Comment by charstars** [comment]
Looking at mapRemove now, it no longer causes a segmentation fault but still a bit of debugging to do using the test driver.
