### ISSUE TITLE
Take a poll on a GitHub Issue

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#11]
Does this work?
/polls 'yes' 'no'

**Comment by powderflask** [comment]
You can vote yes or no above -- poll updates in real-time.
Here's how:
  - start here:  https://app.gh-polls.com/
  - add your poll options
  - "Generate"  and copy the "Markdown"
  - paste into a comment on GitHub Issue - Cool!

**Comment by stargazer28** [comment]
Awesome!
