### ISSUE TITLE
Bug in oneChildDelete()

### ISSUE THREAD

**Issue by charstars** [CapU-CompSci/MapADT-220-2018#110]

**Comment by leviffs** [comment]
Hey, I noticed that there is going to probably be an issue with my twochilddelete function for small trees. If there is a tree with one left and on right node the variables "smallest" and "largest" will be NULL. I would fix it but have to study for DE's, you dont have to fix it but we need there to be a case for this. Good luck

**Comment by charstars** [comment]
I haven't been able to test twoChildDelete() because the tree only inserts to the right at the moment. I am also going to start on DE's so I am leaving that fix up to someone else and will get back to twoChild later. Possibly we can test it together
