### ISSUE TITLE
mapInsert() only inserts to the right in treemap.c

### ISSUE THREAD

**Issue by charstars** [CapU-CompSci/MapADT-220-2018#111]

**Comment by leviffs** [comment]
thats curious, I thought I had fixed this last night. If you are using the map-test.c test driver then that could be the issue with it, b/c   a<b<c<d.

**Comment by charstars** [comment]
Hmm okay. Might make some changes to test driver and see what happens

**Comment by powderflask** [comment]
This seems to work fine -- I think @charstars is right, was just the test data being inserted in sorted order.  That creates one long linear branch -- think that through if you don't see why.
