### ISSUE TITLE
mapInsert() does not change the value for a key if HasKey(map, key) == true

### ISSUE THREAD

**Issue by Karan-Nedungadi** [CapU-CompSci/MapADT-220-2018#113]
This issue arises for both hashmap.c and treemap.c, I will be fixing treemap.c.

**Comment by Karan-Nedungadi** [comment]
This issue will stay up as a similar problem exists in hashmap.c

**Comment by reecewhitehead** [comment]
i am confused, i just checked hashmap for the insert function and it appears to be working as it should, do you mind expanding on the issue you found?

**Comment by Karan-Nedungadi** [comment]
Oh never mind, realized I was reading the output wrong.
