### ISSUE TITLE
wordcloud.c frequency print 

### ISSUE THREAD

**Issue by reecewhitehead** [CapU-CompSci/MapADT-220-2018#117]

**Comment by ttiim** [comment]
can we do this to print them off?

create another search tree that has integer keys, insert all the entries to this new search tree, and use an in-order traversal to read off the entries in frequency order.

**Comment by powderflask** [comment]
This is totally possible, and a good idea.  A List or a simple array would also work, just not as efficiently.  
All we really need here is:
  1) Definition for an "Entry" struct -- a fequency-word pair (int, char*)
  2) An ordered data structure of "Entries" with an insertSorted algorithm (a BST is a natural).   
For each key in the map keySet, get the value, create an Entry and insertSorted(entry).
Then read off the entries in sorted order, as suggested.  
Notice this can be a very paired-down data structure -- we only need a couple operations!

**Comment by ttiim** [comment]
struct entry{
	int frequency;
	char* word;
};    //already defined in treemap.h
map_t printwordmap = mapcreate();  //defined in API map.h
get each key and its value from keytype* mapKeySet(map_t * map)
create an "entry" and then mapinsert(printwordmap, word, frequency)
inorderprint(printwordmap);  //make sure to print in tabular form
destroy(*printwordmap)

**Comment by ttiim** [comment]
so something similar to this? 

struct entry{
	int frequency;
	char* word;
};  // already defined in treemap.h
map_t printwordmap = mapcreate();  // defined in API map.h
get each key and its value from keytype* mapKeySet(map_t * map)
create an "entry" and then mapinsert(printwordmap, word, frequency)
inorderprint(printwordmap);
destroy(*printwordmap)

//should work with map and hash

**Comment by powderflask** [comment]
Yeah - exactly.  Unfortunately, because of the way C works, we need to define an entirely new map ADT for this operation simply because the keytype and itemtype are different than those we need in the first half of the program.
Higher-level languages, like Python and Java, have language support to solve this problem, but "dynamic typing" is awkward in C.  There are solutions, but they make your code very hiroglyphic -- generally easiest to make a copy, change type names, and do some careful namespace management.

**Comment by powderflask** [comment]
Oh -- one clarification:  A `Map` is not really this right abstraction here -- items in a `Map` are unordered, so there is no `inorderprint()` operation.  When I read this, I was thinking of a Binary Tree, and I suspect you were too.

**Comment by reecewhitehead** [comment]
my thoughts were to use mapkeyset() and take the array of keys and use mapGet to get the value, iterate through all of the keys and save the highest value entry, print that one and delete that key from the array via shift left algorithm, rinse and repeat until there are no more entries in the key array.

**Comment by ttiim** [comment]
@powderflask  yeup of course. my bad.
@reecewhitehead  i think both methods work, creating the bst is more efficient (log(n) versus linear) and makes for some more elegant code

**Comment by ttiim** [comment]
@reecewhitehead : if youve got your solution for it then go for it- but the seg fault is a pain to debug.
