### ISSUE TITLE
Tool for Team Communication

### ISSUE THREAD

**Issue by stargazer28** [CapU-CompSci/MapADT-220-2018#12]
Two options that were brought up in class were Slack and Discord. Discuss below.

**Comment by powderflask** [comment]
See #11 for how to add a poll tool

**Comment by stargazer28** [comment]
Please state which other alternative if you choose other!

[![](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Slack)](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Slack/vote)
[![](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Discord)](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Discord/vote)
[![](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Other)](https://api.gh-polls.com/poll/01C9TCF2QMVDRGNS26HJJCQ04N/Other/vote)

**Comment by powderflask** [comment]
Jumping the gun here (sorry stargazer) -- I found I was allowed to create a 2nd free slack channel.  Subscribe here:  https://join.slack.com/t/cap-comp220/shared_invite/enQtMzM4OTY3OTE4MDY1LWE3ODY0ZDE5NWFiOTBiODhiZmZlNWNiZmRiNDZmODNkNDQyNzBkNjI2ZThkYTViM2FmZjVhODA5MjIwMzg1OGY
