### ISSUE TITLE
why is there map-test.c and test-map.c?

### ISSUE THREAD

**Issue by Karan-Nedungadi** [CapU-CompSci/MapADT-220-2018#43]
test-map.c should not have the map function coded. That should be only done in treemap.c

**Comment by Rob-A-Bell** [comment]
Test-map.c looks like it was made to be ignored. Maybe to test some functions?

map-test.c is the test driver for the application. It should work for either map data type

**Comment by awakkary** [comment]
test-map.c is on Josh's computer. He should copy this code on his disk before removing it here.

**Comment by joshyeh** [comment]
Yeah that was my bad, it was just to test some functions, i'll delete it.
