### ISSUE TITLE
wordcloud version 1.0 

### ISSUE THREAD

**Issue by ttiim** [CapU-CompSci/MapADT-220-2018#51]
develop main algorithm and problem solving

**Comment by powderflask** [comment]
Remember that this application needs to work with ANY map implementation -- it should rely ONLY on the public API defined in map.h
I see you added some logic that is very specific the Tree implementation -- that won't fly when we try to build the project with the Hash Table implementation!!

**Comment by powderflask** [comment]
I fixed a few minor errors so this compiles -- would like to push up changes, but want to be sure I'm not treading on Karan's work.  @Karan-Nedungadi - please let me know here or on Slack if I can push the changes for #71

**Comment by Karan-Nedungadi** [comment]
Yes, you can push changes.

**Comment by Karan-Nedungadi** [comment]
Tim and I are just testing and collaborating code. To see what best fits.
