### ISSUE TITLE
Add entryFind function to treemap.c that returns a pointer to the entry with the specified key.

### ISSUE THREAD

**Issue by awakkary** [CapU-CompSci/MapADT-220-2018#54]
We already have a function returning an integer value from a specified entry, but we should have one that returns a pointer to an entry.

**Comment by awakkary** [comment]
Just realized this won't work in the hashmap implementation, it will have to be done in only the treemap version.

**Comment by powderflask** [comment]
I agree with this approach in general:  
 - write helper functions to return an entry_t (or better, and entry_t*)
 - call those to implement functions that need to return keys or values from the entry.

To see an example of this in action, look in 'treemap.c` at the solution for `mapKeySet()`, which calls an helper, `getEntries` to do the bulk of the work.

**Comment by awakkary** [comment]
This function has been implemented in treemap.c.
