### ISSUE TITLE
issues with mapGet()

### ISSUE THREAD

**Issue by Karan-Nedungadi** [CapU-CompSci/MapADT-220-2018#59]
what should mapGet() in treemap.c return if the tree is empty or key not found?

I believe that the most suitable value would be -1, as (from what I know) no key should store a value less than zero.

**Comment by Karan-Nedungadi** [comment]
another problem with mapGet() is that bstFind() is called but that function does not exist anywhere.

**Comment by powderflask** [comment]
the API for mapGet() has a pre-condition:
* PRE: mapHasKey(key)
You can just:   assert(mapHasKey(key);
-- it is the callers responsibility to ensure the map contains the given key before doing a Get.

**Comment by powderflask** [comment]
Karan is right:  `mapGet()` is making what I think should be a recursive call back to `mapGet()`, but calls undefined function `bstFind()` instead.  The algorithm is also incorrect in that it does not `return` the result from the would-be recursive call.

Here's how I would fix this:
1. write the recursive tree private helper function `bstNode_t* bstFind(BinaryTree t)`
2. write `mapGet(map_t map)` to simply call the helper function to do the actual work, and return the node's entry value.

Notice how for internal helper functions, I use the type `BinaryTree`, but for external public interface, I use the public `map_t` type.  These types are compatible -- they are the same thing, but one is for public consumption, whereas the other is an implementation detail (but much more relevant to someone implementing an internal helper function!)

**Comment by keatonzx** [comment]
I believe this has been fixed. The file will still not compile due to remove and size.
