### ISSUE TITLE
key set

### ISSUE THREAD

**Issue by Rob-A-Bell** [CapU-CompSci/MapADT-220-2018#64]
/*
* returns a dynamic array containing all the Map Keys (in any sequence)
* it is the caller's responsibility to free the returned array.
*/
keytype keySet(map_t * map); //keytype is a char* already
If the keytype is a char* already, should this not be a DOUBLE STAR?
 This is going to be an array of char* i guess. What do you folks think?

**Comment by powderflask** [comment]
Yes!   that should read:
`keytype* mapKeySet(..._)`

P.S  you better do a pull -- I changed the name of that function to make it consistent with the rest of the API (see #60)

**Comment by Rob-A-Bell** [comment]
Wonderful, on it

**Comment by Rob-A-Bell** [comment]
Done

**Comment by powderflask** [comment]
Good spot Rob
