### ISSUE TITLE
Add mapPrint() function to generic map.h API?

### ISSUE THREAD

**Issue by Rob-A-Bell** [CapU-CompSci/MapADT-220-2018#65]
Should the map.h have a print function, either to print the entire map or a single piece of data? Or would the tree/hash maps take care of it themselves?

**Comment by powderflask** [comment]
We could add a `mapPrint()` function to the public API if that seems like it would be useful.  Might be very helpful for debugging purposes...
Each implementation would have to supply its own version -- I think its a good idea.

**Comment by charstars** [comment]
I will create a mapPrint() function for treemap.c

**Comment by charstars** [comment]
mapPrint() added for treemap.c has not been tested

**Comment by rickycheung2** [comment]
I'll create the mapPrint() function for hashmap.c

**Comment by rickycheung2** [comment]
I added mapPrint to hashmap.c and added function prototype to map.h API.
Both mapPrint functions in treemap.c and hashmap.c seem to be working.
