### ISSUE TITLE
Fix compilation errors in map-test.c

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#70]
`> gcc -c map-test.c`
Should compile cleanly... doesn't

**Comment by powderflask** [comment]
Done!

**Comment by keatonzx** [comment]
Everything in the file was deleted, was this a mistake?

**Comment by powderflask** [comment]
No idea what happened there - Yeesh!  Seemed like such a routine commit.  thanks for fixing it Keaton.

**Comment by powderflask** [comment]
Or not ... assume you are on it -- go for it.

**Comment by keatonzx** [comment]
I was just making a issue about this, I was not passing the address

**Comment by powderflask** [comment]
Looks like @Rob-A-Bell restored it, but with all the original syntax errors -- are you taking on fixing all the compilation errors?

**Comment by keatonzx** [comment]
Yes I believe I have all the compilation errors fixed when calling insert and delete, which I think are the only errors
