### ISSUE TITLE
Develop algorithm for treemap keySet()

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#72]
`treemap.c`
The current algorithm for `mapKeySet()` calls helper `traverseInOrder()' to get successive keys.
But that is a recursive traversal algorithm -- it visits every node in the tree - can't return one node at a time.   This approach won't work.

**Comment by powderflask** [comment]
A function with the type of behaviour desired here is called a "generator".  A generator can "yield" a value in the middle of a loop and the loop will pick up where it left off the next time the generator function is called.  Generator functions exist in Python, but not in C :-(

In C, we would have to simulate this using an Iterator object -- I showed algorithms for a set of tree iterators for different traversals in class.  You might recall, they are a bit tricky to code, requiring a stack or a queue them!

An easier, more direct method to solve this problem is to pass the array directly into the recursive traversal function, along with the index of the next slot to fill.  This is the "recursive with state" pattern we discussed in class-- it is a bit tricky to think through, but simple to code.  When the traversal algorithm is "processing the current node", simply plop the value into the array at the current index, and increment the index.  
Note that the index MUST be passed by reference, so it acts as an In-Out parameter and thus there is a single index variable shared among all the recursive calls.
It will be relatively easy to retrofit the "recursion with state" solution onto the existing code, but until then `treemap.c` does not compile (#68 )

**Comment by charstars** [comment]
I essentially implemented this into the most recent version of the function but it is still not compiling correctly. I feel like i am still having trouble with what you mean by passing the index by reference and what that would like in the context of the function. This is what I have so far:


keytype traverseInOrder(map_t map, keytype array){
	if(map != NULL){ 
	        int i=0;
	        keytype newArray = array;
		traverseInOrder(map->left);
		array[i] = map->entry.key;
		i++;
		traverseInOrder(map->right);	
	}									
}

**Comment by powderflask** [comment]
Sure -- I'll jump in and help in the code -- get any changes you want committed quick ;-)

**Comment by powderflask** [comment]
@charstars - your idea was on the right track, but you made a couple rookie errors:
 1. you are passing something called "array", but it is not declared as an actual array;
 2. you have a local variable i to track to the current index, but each recursive function call will define its own local `i`, which will always be initialized to zero.  We need a way for all recursive calls to share `i`;
 3. your recursive calls do not call the function you are defining -- they are not passing the array back into the recursive calls.

I wrote the code I was thinking of -- please review it and let me know if it makes sense.

**Comment by powderflask** [comment]
P.S.  to throw away your local changes so they don't conflict with the commit above, try:
> git checkout --theirs treemap.c
or
> git revert HEAD
(this last one reverts your entire source tree to be the same as the current repo, so be careful).

**Comment by powderflask** [comment]
@charstars - please close this ticket when you have reviewed code and are satisfied that my algorithm will work.

**Comment by charstars** [comment]
Yes I will joseph, Sorry I haven't had any time to look at it after this morning. I have many things due tomorrow. I will start working on compsci after classes and will review the code tomorrow afternoon :)
