### ISSUE TITLE
mapInsert() crashes program treemap.c

### ISSUE THREAD

**Issue by leviffs** [CapU-CompSci/MapADT-220-2018#74]

**Comment by leviffs** [comment]
I believe the problem is mapInsert calls mapHasKey which calls mapGet which calls mapHaskey which asserts the map has a key.

**Comment by powderflask** [comment]
Good diagnosis Levi!  Yes -- `mapInsert()` can't call `mapGet()`, since the later calls the former to do it's work!!  That sets up an unintended, infinite recursive loop between the two.

**Comment by stargazer28** [comment]
Fixed, see #67.
