### ISSUE TITLE
Add initial WordCloud app file

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#8]
Create the basic structure for the WordCloud app.

The app should use a typedef to define the Map Type so that it is simple to define which Map implementation to use for the app.
Depends on issues #1 & #2 - until then a "dummy" typedef can be used to define the Map Type (say as an int), so that work can proceed on the app code independently until those are done.

**Comment by ttiim** [comment]
Karan and i have uploaded this to develop.
