### ISSUE TITLE
BUGS in treemap.c

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#80]
I have marked a number of lines of code in `treemap.c` with the comment BUG.
None of these are difficult to fix, but each will require a little thinking to figure out what was intended and re-write the code to achieve the actual goal.

**Comment by Karan-Nedungadi** [comment]
I'll fix the bugs in findParent().

**Comment by charstars** [comment]
currently working on mapRemove()
