### ISSUE TITLE
treemap.c does not compile

### ISSUE THREAD

**Issue by powderflask** [CapU-CompSci/MapADT-220-2018#88]
Blame:   https://github.com/CapU-CompSci/MapADT-220-2018/commit/4b7f9443b99f3e3810131eaabd8f05cbb86e4456

Looks like this re-factor (which was a good idea) was attempted by hand (mistake 1 -- use replace instead!); and not compiled before committing (mistake 2 -- always ensure the code you commit compiles, ideally tested)

**Comment by awakkary** [comment]
Problem solved. Thanks for letting me know so quickly
