### ISSUE TITLE
mapRemove causing segmenation fault 

### ISSUE THREAD

**Issue by keatonzx** [CapU-CompSci/MapADT-220-2018#90]

**Comment by Karan-Nedungadi** [comment]
any progress on this?
I was going to work on the findParent bug (#100) because that seems the reason for mapRemove messing up. Hopefully, this can be resolved soon.

**Comment by joshyeh** [comment]
I fixed the segmentation fault for the given map test program, but for other cases for mapRemove they will also cause segmenation fault because of the corresponding sub-delete functions (leaf delete, etc.), which is all caused because of the insert function which doesn't seem to work properly.

**Comment by Karan-Nedungadi** [comment]
So are you still working on this issue?
I noticed findParent is segfaulting and deletetwoChildnode() can be improved, so I wanna make some tweaks.

**Comment by joshyeh** [comment]
I just committed what I have so far. I will be working on it (trying to fix the insert issue), but feel free to work on it as well.
