### ISSUE TITLE
debugging mapRemove()

### ISSUE THREAD

**Issue by charstars** [CapU-CompSci/MapADT-220-2018#92]

**Comment by charstars** [comment]
Still debugging mapRemove. It's working in the two child case, but not the leaf node case.

**Comment by charstars** [comment]
leaf node case is fixed as well as one child case. Still need to test two child case

**Comment by charstars** [comment]
I added some debugging print statements to treemap.c still can't figure out why its not working

**Comment by powderflask** [comment]
This appears to work now.  Maybe @joshyeh fixed it with #116
