### ISSUE TITLE
mapKeySet() segmentation fault

### ISSUE THREAD

**Issue by keatonzx** [CapU-CompSci/MapADT-220-2018#93]
The issue is with getEntires() I do not think it should be a void function.

**Comment by awakkary** [comment]
My understanding is that since it is populating an array that is being passed by reference as a parameter, that it does not return an array, but fills it as a side effect.

**Comment by keatonzx** [comment]
Ah yes, that is not the issue. if you write 
        printf("here\n");
	fflush(stdout);

after getEntries(); it will not print, so that is the cause of the fault

**Comment by keatonzx** [comment]
Upon further flushing it seems like 
		entries[*index] = &(map->entry);
is the cause
