### ISSUE TITLE
mapInsert() BUG? 

### ISSUE THREAD

**Issue by leviffs** [CapU-CompSci/MapADT-220-2018#98]
When inserting a new node the function considers the key when organizing and inserting the node. Noticed this when the tree failed to print inOrder.If this is wrong let me know.

**Comment by joshyeh** [comment]
Yeah, every time a new node is inserted its always on the right regardless of the value.

**Comment by leviffs** [comment]
As far as I can tell I agree. As a consequence mapGet doesn't work when we randomize the keys and values of the tree, I think it's because the keys are getting compared by their address. I'm not sure how to fix this.

**Comment by leviffs** [comment]
on it
